// <auto-generated />
using System;
using ClubesApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubesApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ClubesDbContext))]
    partial class ClubesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubesApi.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Deuda", b =>
                {
                    b.Property<Guid>("DeudaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("Vencimiento")
                        .HasColumnType("date");

                    b.HasKey("DeudaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CapitanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EquipoId");

                    b.HasIndex("CapitanId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Espacio", b =>
                {
                    b.Property<Guid>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PctSena")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VentanaCancelacionHoras")
                        .HasColumnType("int");

                    b.HasKey("EspacioId");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.EventoPartido", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EventoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EventosPartido");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Gasto", b =>
                {
                    b.Property<Guid>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("GastoId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Jugador", b =>
                {
                    b.Property<Guid>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JugadorId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ValidadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.HasIndex("ValidadoPor");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PartidoId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("EspacioId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CanceladaEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<decimal?>("MontoReintegrado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspacioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Torneo", b =>
                {
                    b.Property<Guid>("TorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PuntosDerrota")
                        .HasColumnType("int");

                    b.Property<int>("PuntosEmpate")
                        .HasColumnType("int");

                    b.Property<int>("PuntosVictoria")
                        .HasColumnType("int");

                    b.Property<string>("SistemaCompetencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TorneoId");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Zona", b =>
                {
                    b.Property<Guid>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TorneoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ZonaId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Deuda", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Deudas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Equipo", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Cliente", "Capitan")
                        .WithMany("EquiposComoCapitan")
                        .HasForeignKey("CapitanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClubesApi.Domain.Entities.Zona", "Zona")
                        .WithMany("Equipos")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitan");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.EventoPartido", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Jugador", "Jugador")
                        .WithMany("Eventos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Partido", "Partido")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Jugador", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Pago", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Reserva", "Reserva")
                        .WithOne("Pago")
                        .HasForeignKey("ClubesApi.Domain.Entities.Pago", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Cliente", "Validador")
                        .WithMany()
                        .HasForeignKey("ValidadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reserva");

                    b.Navigation("Validador");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Partido", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Espacio", "Espacio")
                        .WithMany("Partidos")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Zona", "Zona")
                        .WithMany("Partidos")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Espacio");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubesApi.Domain.Entities.Espacio", "Espacio")
                        .WithMany("Reservas")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Zona", b =>
                {
                    b.HasOne("ClubesApi.Domain.Entities.Torneo", "Torneo")
                        .WithMany("Zonas")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Deudas");

                    b.Navigation("EquiposComoCapitan");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Espacio", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Jugador", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Torneo", b =>
                {
                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("ClubesApi.Domain.Entities.Zona", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
